name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover tests
